"""
    Abfallnavi API

    Termine für Leerung des Abfalls nach Abfallart (Papier, Restmüll, ...). Beispielswerte sind für das Rathaus Nürnberg (Hauptmarkt 18, Nürnberg).  # Kommunen / Regionen  Das System ist in diverse Regionen unterteilt. Zu einer `Region` gehören ein oder mehrere Kommunen.  * `aachen`: Aachen * `zew2`: AWA Entsorgungs GmbH * `aw-bgl2`: Bergisch Gladbach * `bav`: Bergischer Abfallwirtschaftverbund * `din`: Dinslaken * `dorsten`: Dorsten * `gt2`: Gütersloh * `hlv`: Halver * `coe`: Kreis Coesfeld * `krhs`: Kreis Heinsberg * `pi`: Kreis Pinneberg * `krwaf`: Kreis Warendorf * `lindlar`: Lindlar * `stl`: Lüdenscheid * `nds`: Norderstedt * `nuernberg`: Nürnberg * `roe`: Roetgen * `solingen`: Solingen * `wml2`: EGW Westmünsterland  # Benutzung  Für die Abfrage von Terminen ist eine Reihe von IDs (von Orten, Straßen und/oder Hausnummern) in Erfahrung zu bringen. Vorsicht:IDs können sich mit der Zeit ändern  1. Orte aus System holen 2. Mit Ort die Straßen abfragen 3. Mit Straße die Hausnummern abfragen 4. Mit Haunummer die möglichen Fraktionen (Müllsorten) abfragen 5. Mit Hausnummer und Fraktionen alle Termine abrufen  Manchmal wird nicht nach Hausnummer unterschieden   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.abfallnavi.api.abholpunkte_api import AbholpunkteApi  # noqa: E501

from deutschland import abfallnavi


class TestAbholpunkteApi(unittest.TestCase):
    """AbholpunkteApi unit test stubs"""

    def setUp(self):
        self.api = AbholpunkteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_hausnummern_pro_strasse(self):
        """Test case for hausnummern_pro_strasse

        Hausnummern in Straße  # noqa: E501
        """
        pass

    def test_ort(self):
        """Test case for ort

        Informationen zu Ort  # noqa: E501
        """
        pass

    def test_orte(self):
        """Test case for orte

        Orte im System  # noqa: E501
        """
        pass

    def test_strassen_pro_ort(self):
        """Test case for strassen_pro_ort

        Straßen im Ort  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
